input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [environment] {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "library-logs-%{environment}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "library-logs" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "${ES_USERNAME:-elastic}"
    password => "${ES_PASSWORD:-elastic}"
    ssl_certificate_verification => false
    index => "%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
  }
}
